config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'search/view'
  resources :admins
  resources :entries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "entries#new"
  get '/search',to: "search#search"
  get '/retrieve',to: "search#view"
  # get '/login', to: redirect('/admins')
  # get '/logout', to: redirect('/admins')
  get '/login',to: 'authentication#login'
  post '/authenticate',to: 'authentication#authenticate'
  get '/logout',to: 'authentication#logout'
end

app/views/admins/_admin.html.erb
<tr id="<%= dom_id admin %>" class="text-center">
  <td>
    <%= admin.username %>
  </td>
  <td>
    <%= link_to "Show this admin", admin %>
  </td>

<!--  <p>-->
<!--    <strong>Pass:</strong>-->
    <%#= admin.password %>
<!--  </p>-->

</tr>

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :superuser, style: "display: block" %>
    <%= form.check_box :superuser %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/_login.html.erb
<%= form_with url: '/login', method:'post' do |login_form| %>
  <div class="d-flex flex-column">
    <div class="flex-row"><%= login_form.label :username, 'Username' %></div>
      <div class="flex-row"><%= login_form.text_field :username %></div>
      <div class="flex-row"><%= login_form.label :password, 'Password' %></div>
      <div class="flex-row"><%= login_form.password_field :password %></div>
    <div class="flex-row"><%= login_form.submit "Attempt Login", class: "btn btn-primary mt-1", id:"login" %></div>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Show this admin", @admin %> |
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Admins</h1>

<% if logged_in?(session['username'],session['token'])&.superuser%>
<table id="admins" class="w-100">
  <tr class="text-center">
    <th>Username</th>
  </tr>
  <% @admins.each do |admin| %>
    <%= render admin %>
  <% end %>
</table>
<div class="justify-content-center text-center mt-xl">
  <%= button_to "New admin", new_admin_path, class: "btn btn-primary",method: :get %>
</div>
<% end %>

app/views/admins/index.turbo_stream.erb
<% turbo_stream.prepend 'admins' do %>
  <%= render "admin",admin: @admin %>
<% end %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @admin %>

<div>
  <%= link_to "Edit this admin", edit_admin_path(@admin) %> |
  <%= link_to "Back to admins", admins_path %>

  <%= button_to "Destroy this admin", @admin, method: :delete %>
</div>