config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  get 'search/view'
  resources :admins
  resources :entries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "entries#new"
  get '/search',to: "search#search"
  get '/retrieve',to: "search#view"
  # get '/login', to: redirect('/admins')
  # get '/logout', to: redirect('/admins')
  get '/login',to: 'authentication#login'
  post '/authenticate',to: 'authentication#authenticate'
  get '/logout',to: 'authentication#logout'
end

app/models/entry.rb
class Entry < ApplicationRecord
  # attr_accessor :name,:time_in,:time_out,:mobile_number
  validates :username, uniqueness: true
  validates :username, presence: true
  validates :time_in,presence: true
  validates :name,presence: true
  # no mobile phone specified due to the fact that a mobile phone may not be available.
  # after_save_commit -> { broadcast_prepend_to "entries", partial: "entries/entry", locals: { quote: self }, target: "entries" }
  # after_destroy_commit -> { broadcast_destroy_to "entries", partial: "entries/entry", locals: { quote: self }, target: "entries" }
  broadcasts_to -> (entry){:entries} #https://blog.corsego.com/turbo-hotwire-broadcasts
  # entries is the name of the parameter passed to turbo stream from parameter in index.html.erb
  # in this case it is entries. entry is the name of the partial of which the broadcast will pass to the stream
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]
  before_action :reject_if_not_authorized, :only => %i[ show index edit update destroy ]

  # GET /entries or /entries.json
  def index
    if logged_in?
      @entries = Entry.all
      respond_to do |format|
        format.html
        format.turbo_stream
      end
    else
      redirect_to root_path
    end
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        flash[:notice] = "entry saved successfully"
        format.html { redirect_to entry_url(@entry) }
        format.json { render :show, status: :created, location: @entry }
      else
        # sloppy hacks but might work
        format.html { render :new, status: :unprocessable_entity,notice: "Entry was unsuccessfully saved " }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      parameters = params.require(:entry).permit(:username,:name, :time_in, :time_out, :mobile_phone,:search)
      # puts parameters.to_h.to_s
      return parameters
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<% if entry %>
<tr id="<%= dom_id entry %>" class="text-center">
  <td>

    <%= entry.username %>
  </td>
  <td>

    <%= entry.name %>
  </td>

  <td>
    <%# entry.time_in.localtime.strftime(" %d/%m/%Y %I:%M %p")%>
    <%= entry.time_in%>
  </td>

  <td>

    <%= entry.time_out&.localtime&.strftime(" %d/%m/%Y %I:%M %p") %>
  </td>

  <td>

    <%= entry.mobile_phone %>
  </td>
  <% if logged_in?(session['username'],session['token']) %>
    <td>
      <%= link_to "Show this entry", entry %>
    </td>
  <% end %>
 </tr>
<% else %>
  <h1> NO LOG ENTRIES FOUND </h1>
<% end %>

app/views/entries/_form.html.erb
<div class="container text-center">
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="d-flex flex-column">
  <div class="flex-row">
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div class="flex-row">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="flex-row">
    <%= form.label :time_in, style: "display: block" %>
    <%= form.datetime_field :time_in,min:DateTime.now,value:DateTime.now.strftime('%FT%T') %>
  </div>

  <div class="flex-row">
    <%= form.label :time_out, style: "display: block" %>
    <%= form.datetime_field :time_out ,value:DateTime.now%>
  </div>

  <div class="flex-row">
    <%= form.label :mobile_phone, style: "display: block" %>
    <%= form.text_field :mobile_phone %>
  </div>

  <div class="flex-row mt-1">
    <%= form.submit %>
  </div>
  </div>
<% end %>
</div>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

<br>
<div>
  <div>
    <%= button_to "Sign Out",entry_path({entry:{time_out:DateTime.now}}),method: :patch %>
  </div>
</div>
<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-center">Entries</h1>

<section>
<%= turbo_stream_from "entries" %>
<table id="entries" class="w-100">
  <tr class="text-center">
    <th>Username</th>
    <th>Name</th>
    <th>Time In</th>
    <th>Time Out</th>
    <th>Mobile Phone</th>
  </tr>
  <%# reverse shows the latest first %>
  <% @entries.reverse.each do |entry| %>
    <%= render entry %>

  <% end %>
</table>
</section>


<div class="justify-content-center text-center">
<p><%= button_to "New entry", new_entry_path,class: "btn btn-primary",method: :get %></p>
</div>

app/views/entries/new.html.erb
<h1 class="text-center">New entry</h1>
<div class="text-center">
<p>If you forget your username, ask an admin and they will tell you what it is.</p>
<p>They can also sign you out if you forget.</p>
</div>
<div>
<%= render "form", entry: @entry %>
</div>
<br>
<% if logged_in? session['username'],session['token'] %>
<div>
  <%= link_to "Back to entries", entries_path %>
</div>
<% end %>

app/views/entries/new.turbo_stream.erb
<% turbo_stream.prepend 'entries' do %>
  <%= render "entry",entry:@entry %>
<% end %>

app/views/entries/search.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entry %>

<div>
  <%= link_to "Edit your signin", edit_entry_path(@entry) %> |
</div>

app/views/entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entry %>

<div>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= link_to "Back to entries", entries_path %>

  <%= button_to "Destroy this entry", @entry, method: :delete %>
</div>

app/views/entries/view.turbo_stream.erb
<% turbo_stream.prepend 'entries' do %>
  <%= render "entry",entry:@entry %>
<% end %>